country_mapping = {
    'MY': 'Malaysia',
    'GB': 'United Kingdom',
    'DE': 'Germany',
    'US': 'United States of America',
    'AU': 'Australia',
    'CA': 'Canada',
    'FI': 'Finland',
    'ES': 'Spain',
    'ID': 'Indonesia',
    'GR': 'Greece',
    'IN': 'India',
    'BR': 'Brazil',
    'PT': 'Portugal',
    'RS': 'Russia',
    'IT': 'Italy',
    'FR': 'France',
    'RO': 'Romania',
    'PL': 'Poland',
    'PH': 'Philippines',
    'IE': 'Ireland',
    'NZ': 'New Zealand',
    'ZA': 'South Africa',
    'NL': 'Netherlands',
    'JM': 'Jamaica',
    'MX': 'Mexico',
    'PK': 'Pakistan',
    'HK': 'Hong Kong',
    'SG': 'Singapore',
    'RU': 'Russia',
    'TR': 'Turkey',
    'EG': 'Egypt',
    'SA': 'Saudi Arabia',
    'BN': 'Brunei Darussalam',
    'JP': 'Japan',
  
}
